[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-social-media-directory"
version = "0.1.0"
dependencies = [
    "flask",
    "gunicorn"
]